import type { Dimension, DimensionId, Persona } from "./types";

export const MODEL_VERSION = "dimensions-v010/personas-v006";

export const dimensions: Dimension[] = [
  {
    id: "D1",
    name: "需求牵引 ↔ 前沿牵引",
    shortName: "需求-前沿",
    leftPole: "客户价值",
    rightPole: "前沿突破",
    description: "判断你更倾向从真实需求出发，还是从新技术和新方法的可能性出发。",
    weight: 1,
  },
  {
    id: "D2",
    name: "交付收敛 ↔ 创新发散",
    shortName: "交付-创新",
    leftPole: "稳定交付",
    rightPole: "探索可能",
    description: "判断你在版本、项目或流程推进中更倾向收敛，还是继续探索。",
    weight: 1,
  },
  {
    id: "D3",
    name: "点位深潜 ↔ 系统全局",
    shortName: "深潜-全局",
    leftPole: "点位深潜",
    rightPole: "系统全局",
    description: "判断你更擅长进入细节，还是看到跨模块、跨团队的整体关系。",
    weight: 1,
  },
  {
    id: "D4",
    name: "快速验证 ↔ 机制严谨",
    shortName: "验证-机制",
    leftPole: "快速验证",
    rightPole: "机制严谨",
    description: "判断你更倾向先复现和试验，还是先理解原因、边界和机制。",
    weight: 1,
  },
  {
    id: "D5",
    name: "独立攻坚 ↔ 协同共创",
    shortName: "独立-协同",
    leftPole: "独立攻坚",
    rightPole: "协同共创",
    description: "判断你更倾向自己先研究清楚，还是尽早拉人共同推进。",
    weight: 0.8,
  },
  {
    id: "D6",
    name: "当期闭环 ↔ 长期正确",
    shortName: "当期-长期",
    leftPole: "当期闭环",
    rightPole: "长期正确",
    description: "判断你更优先当前目标，还是长期结构、质量和正确性。",
    weight: 1.2,
  },
  {
    id: "D7",
    name: "极致效果 ↔ 资源均衡",
    shortName: "效果-资源",
    leftPole: "极致效果",
    rightPole: "资源均衡",
    description: "判断你更追求效果上限，还是兼顾成本、资源、时间和可行性。",
    weight: 1,
  },
  {
    id: "D8",
    name: "灵活响应 ↔ 治理稳健",
    shortName: "灵活-治理",
    leftPole: "灵活响应",
    rightPole: "治理稳健",
    description: "判断你更倾向快速找到可行路径，还是遵守流程、质量和风险边界。",
    weight: 1,
  },
  {
    id: "D9",
    name: "私下定位 ↔ 公开同步",
    shortName: "私下-公开",
    leftPole: "先私下确认",
    rightPole: "尽早公开同步",
    description: "判断你更倾向确认后同步，还是尽早让相关方知情。",
    weight: 0.8,
  },
  {
    id: "D10",
    name: "人工执行 ↔ AI 委托",
    shortName: "人工-AI",
    leftPole: "人工掌控",
    rightPole: "AI 委托",
    description: "判断你更倾向人工完成关键任务，还是把任务拆给 AI 并设置验收。",
    weight: 1.2,
  },
];

export const dimensionIds: DimensionId[] = dimensions.map((item) => item.id);

const vector = (
  d1: number,
  d2: number,
  d3: number,
  d4: number,
  d5: number,
  d6: number,
  d7: number,
  d8: number,
  d9: number,
  d10: number,
): Record<DimensionId, number> => ({
  D1: d1,
  D2: d2,
  D3: d3,
  D4: d4,
  D5: d5,
  D6: d6,
  D7: d7,
  D8: d8,
  D9: d9,
  D10: d10,
});

export const personas: Persona[] = [
  {
    id: "P01",
    name: "灯塔探索者",
    englishName: "Lighthouse Explorer",
    nickname: "技术远光灯",
    imagePath: "personas/1灯塔探索者.webp",
    slogan: "看见下一代的算力路口。",
    description: "你习惯从长期趋势和新的可能性出发，帮助团队提前看见方向变化。",
    strengths: ["识别长期技术方向", "提出新可能性", "突破当前假设"],
    blindSpots: ["可能超前于交付节奏", "低估迁移成本", "探索过多收敛不足"],
    collaborationStyle: "给探索设置期限、证据要求和输出格式。",
    recommendedPartnerIds: ["P04", "P02", "P10"],
    vector: vector(75, 85, 72, 78, 50, 78, 45, 50, 52, 74),
    distanceBonus: -442.2,
  },
  {
    id: "P02",
    name: "架构织网者",
    englishName: "Systems Weaver",
    nickname: "全局拓扑管理员",
    imagePath: "personas/2架构织网者.webp",
    slogan: "先看边界，再谈实现。",
    description: "你会把局部问题放回系统结构中，关注边界、接口和长期演化。",
    strengths: ["系统思考", "识别跨模块风险", "设计长期结构"],
    blindSpots: ["可能过度设计", "紧急场景收敛偏慢", "抽象讨论时间较长"],
    collaborationStyle: "提前给完整上下文，并要求输出分阶段方案。",
    recommendedPartnerIds: ["P04", "P03", "P08"],
    vector: vector(55, 65, 92, 82, 55, 85, 45, 55, 75, 55),
    distanceBonus: 465.06,
  },
  {
    id: "P03",
    name: "深潜攻坚者",
    englishName: "Deep Diver",
    nickname: "人形单步调试器",
    imagePath: "personas/3深潜攻坚者.webp",
    slogan: "问题可以躲，但躲不过深挖。",
    description: "你能长时间聚焦复杂问题，直到找到根因或突破点。",
    strengths: ["复杂问题攻坚", "根因分析", "深度专业积累"],
    blindSpots: ["容易陷入局部最优", "对外同步不足", "排查时间可能过长"],
    collaborationStyle: "给明确问题、期限和阶段性同步要求。",
    recommendedPartnerIds: ["P08", "P04", "P09"],
    vector: vector(40, 50, 40, 88, 40, 70, 38, 45, 35, 35),
    distanceBonus: -94.64,
  },
  {
    id: "P04",
    name: "交付推进器",
    englishName: "Delivery Driver",
    nickname: "里程碑推进器",
    imagePath: "personas/4交付推进器.webp",
    slogan: "让事情真正发生。",
    description: "你关注目标、风险和结果，善于把模糊状态推进到明确闭环。",
    strengths: ["目标拆解", "阻塞识别", "推动决策和闭环"],
    blindSpots: ["可能推进过快", "低估技术债", "信息不足时催促决策"],
    collaborationStyle: "直接给出状态、影响、需要的决策和时间点。",
    recommendedPartnerIds: ["P06", "P02", "P10"],
    vector: vector(65, 10, 55, 30, 60, 10, 55, 45, 75, 65),
    distanceBonus: 26.64,
  },
  {
    id: "P05",
    name: "客户同行者",
    englishName: "Customer Champion",
    nickname: "需求翻译机",
    imagePath: "personas/5客户同行者.webp",
    slogan: "从客户真实场景出发。",
    description: "你善于把模糊反馈翻译成真实需求，并在多方之间寻找共赢。",
    strengths: ["需求澄清", "客户信任", "价值判断"],
    blindSpots: ["可能被短期需求牵引", "承担过多沟通压力", "技术取舍参与不足"],
    collaborationStyle: "区分客户表达、真实需求和候选方案。",
    recommendedPartnerIds: ["P01", "P10", "P02"],
    vector: vector(5, 35, 65, 50, 90, 45, 60, 50, 85, 50),
    distanceBonus: -946.34,
  },
  {
    id: "P06",
    name: "可靠守门人",
    englishName: "Reliability Guardian",
    nickname: "上线前最后一道闸",
    imagePath: "personas/6可靠守门人.webp",
    slogan: "稳定是系统能力，不是运气。",
    description: "你重视质量、稳定性、回归和责任边界，能降低系统性风险。",
    strengths: ["风险识别", "质量把关", "事故预防"],
    blindSpots: ["可能偏保守", "紧急恢复偏慢", "创新实验容忍度低"],
    collaborationStyle: "同时输出风险等级、影响范围和缓解方案。",
    recommendedPartnerIds: ["P04", "P01", "P14"],
    vector: vector(45, 20, 70, 75, 55, 55, 40, 90, 65, 30),
    distanceBonus: -28.08,
  },
  {
    id: "P07",
    name: "极致雕琢者",
    englishName: "Performance Artisan",
    nickname: "纳米级效果雕刻师",
    imagePath: "personas/7极致雕琢者.webp",
    slogan: "还能更快、更省、更精确。",
    description: "你追求效果、质量或效率上限，愿意为关键改进持续投入。",
    strengths: ["指标敏感", "持续优化", "建立高标准"],
    blindSpots: ["可能过度优化", "忽略交付成本", "边际收益判断不足"],
    collaborationStyle: "设定优化阈值、时间盒和前后对比要求。",
    recommendedPartnerIds: ["P10", "P04", "P13"],
    vector: vector(35, 45, 45, 88, 40, 60, 38, 60, 35, 40),
    distanceBonus: -625.56,
  },
  {
    id: "P08",
    name: "生态连接者",
    englishName: "Ecosystem Connector",
    nickname: "跨部门路由器",
    imagePath: "personas/8生态连接者.webp",
    slogan: "让信息找到人，让人找到共识。",
    description: "你善于连接人和信息，减少误解、重复劳动和部门间摩擦。",
    strengths: ["跨团队协同", "信息同步", "推动共识"],
    blindSpots: ["沟通成本较高", "容易承接过多协调工作", "可能被请求淹没"],
    collaborationStyle: "明确责任边界、结论和待办，不让信息在你这里丢包。",
    recommendedPartnerIds: ["P03", "P02", "P12"],
    vector: vector(60, 55, 90, 45, 95, 55, 60, 40, 95, 70),
    distanceBonus: 232.19,
  },
  {
    id: "P09",
    name: "工具链侦探",
    englishName: "Toolchain Detective",
    nickname: "配置现场调查员",
    imagePath: "personas/9工具链侦探.webp",
    slogan: "总有一层链路在说谎。",
    description: "你对工具、配置、流程和版本差异敏感，善于找到隐藏原因。",
    strengths: ["链路排查", "环境差异识别", "沉淀排查路径"],
    blindSpots: ["追根因可能过久", "忽略业务恢复优先级", "对异常噪音容忍度低"],
    collaborationStyle: "提供完整版本、环境、日志和复现步骤。",
    recommendedPartnerIds: ["P04", "P08", "P14"],
    vector: vector(40, 30, 60, 95, 25, 55, 40, 50, 35, 55),
    distanceBonus: 308.3,
  },
  {
    id: "P10",
    name: "持续进化者",
    englishName: "Continuous Evolver",
    nickname: "迭代升级引擎",
    imagePath: "personas/10持续进化者.webp",
    slogan: "每一次复盘都变成下一次版本。",
    description: "你相信能力来自持续反馈、复盘和迭代，愿意把经验沉淀成更好的方法。",
    strengths: ["持续学习", "复盘沉淀", "小步迭代", "反馈吸收"],
    blindSpots: ["可能迭代过频", "对不完善状态容忍度低", "容易增加改进成本"],
    collaborationStyle: "明确改进目标、度量方式和回顾节奏，让变化可追踪。",
    recommendedPartnerIds: ["P04", "P07", "P13"],
    vector: vector(55, 75, 45, 65, 55, 80, 65, 65, 65, 80),
    distanceBonus: -1231.86,
  },
  {
    id: "P11",
    name: "合规护航者",
    englishName: "Compliance Navigator",
    nickname: "边界感天花板",
    imagePath: "personas/11合规护航者.webp",
    slogan: "先确认边界，再加速前进。",
    description: "你关注流程、权限、合同、数据和长期安全边界。",
    strengths: ["风险预防", "流程设计", "长期安全意识"],
    blindSpots: ["可能抑制速度", "例外处理偏谨慎", "需要分级机制"],
    collaborationStyle: "输出风险等级、影响范围和合规替代路径。",
    recommendedPartnerIds: ["P04", "P01", "P14"],
    vector: vector(50, 20, 65, 60, 70, 75, 65, 98, 70, 20),
    distanceBonus: 1124.9,
  },
  {
    id: "P12",
    name: "变革推动者",
    englishName: "Change Driver",
    nickname: "组织换挡器",
    imagePath: "personas/12变革推动者.webp",
    slogan: "把合理的不满变成新的工作方式。",
    description: "你能察觉旧方式的局限，并推动团队完成从共识到落地的转变。",
    strengths: ["变革共识", "跨职能推动", "组织敏锐度", "落地推进"],
    blindSpots: ["变化节奏可能过快", "容易低估团队适应成本", "阻力处理消耗较大"],
    collaborationStyle: "先讲清原因、收益和过渡方案，再明确阶段责任。",
    recommendedPartnerIds: ["P04", "P11", "P16"],
    vector: vector(60, 80, 85, 50, 85, 80, 55, 40, 90, 70),
    distanceBonus: 624.21,
  },
  {
    id: "P13",
    name: "模型雷达",
    englishName: "Model Radar",
    nickname: "新模型情报台",
    imagePath: "personas/13模型雷达.webp",
    slogan: "新工具、新模型、新价格，雷达先响。",
    description: "你对新模型、新工具、新方法、成本和生态变化高度敏感。",
    strengths: ["技术扫描", "性价比比较", "早期机会识别"],
    blindSpots: ["容易追新过密", "低估迁移成本", "需要收敛机制"],
    collaborationStyle: "输出对比矩阵、实测计划和放弃条件。",
    recommendedPartnerIds: ["P04", "P10", "P02"],
    vector: vector(70, 85, 75, 55, 70, 70, 85, 35, 90, 80),
    distanceBonus: 702.86,
  },
  {
    id: "P14",
    name: "Agent 牧羊人",
    englishName: "Agent Shepherd",
    nickname: "AI 任务调度台",
    imagePath: "personas/14Agent牧羊人.webp",
    slogan: "敢委托，也敢拉回来。",
    description: "你敢把多步任务交给 AI，并会设置边界、检查点和验收标准。",
    strengths: ["AI 工作流设计", "任务拆解", "效率提升"],
    blindSpots: ["可能过度委托", "高风险场景需人工复核", "权限边界要更谨慎"],
    collaborationStyle: "明确目标、上下文、禁区、工具权限和验收标准。",
    recommendedPartnerIds: ["P06", "P09", "P11"],
    vector: vector(70, 20, 85, 60, 75, 50, 70, 75, 90, 95),
    distanceBonus: 1255.08,
  },
  {
    id: "P15",
    name: "多边形战士",
    englishName: "Polygon Warrior",
    nickname: "多线程补位手",
    imagePath: "personas/15多边形战士.webp",
    slogan: "哪里需要，就能切换到哪里。",
    description: "你能在多个角色、任务和语境之间切换，并快速补上团队缺口。",
    strengths: ["多任务切换", "跨职能补位", "适应变化", "执行跨度大"],
    blindSpots: ["容易承接过多任务", "深度工作时间不足", "边界感容易被稀释"],
    collaborationStyle: "用明确优先级和暂停机制保护重点任务。",
    recommendedPartnerIds: ["P04", "P16", "P12"],
    vector: vector(65, 50, 85, 50, 80, 35, 65, 25, 80, 65),
    distanceBonus: -745.37,
  },
  {
    id: "P16",
    name: "协同润滑者",
    englishName: "Collaboration Lubricator",
    nickname: "低摩擦协调器",
    imagePath: "personas/16协同润滑者.webp",
    slogan: "让协作顺畅，让分歧可谈。",
    description: "你善于降低沟通摩擦，在紧张场景中保持信息流动和合作氛围。",
    strengths: ["冲突缓解", "氛围维护", "共识搭建", "沟通转译"],
    blindSpots: ["可能回避必要冲突", "情绪劳动较重", "决策推进偏柔"],
    collaborationStyle: "先接住分歧，再把问题转成共同目标和可执行选项。",
    recommendedPartnerIds: ["P12", "P15", "P08"],
    vector: vector(55, 35, 70, 45, 95, 40, 60, 70, 95, 65),
    distanceBonus: -625.19,
  },
];

export const personaById = new Map(personas.map((persona) => [persona.id, persona]));
